### ISSUE TITLE
Multiple Spelling / Grammar Errors

### ISSUE THREAD

**Issue by HiltonGiesenow** [lukePeavey/quotable#14]
First of all, thanks **so much** for this project, I'm using inside a personal project of my own and love seeing the quotes!

There are, unfortunately, a whole bunch of spelling and grammar errors in a lot of the quotes. I'd love to help with these, but they're not part of the project itself, as far as I can see. Is there a way I could get access to the data store to help, if you'd like me to pitch in?

**Comment by HiltonGiesenow** [comment]
lol - I misspelled "grammar" above ;)

**Comment by lukePeavey** [comment]
Glad you are enjoying it! There are quite a few errors in the quotes.  I working on this now.  I've just finished overhauling the authors collection. My next step is cleaning up the existing quotes and adding new ones. If you are interesting in helping maintain/edit the quotes, let me know!

**Comment by lukePeavey** [comment]
@HiltonGiesenow

I just wanted to follow up one more time before I close this issue. I've done quite a lot of work on improving the quality of the content since you originally posted this. 

- Removed all duplicate authors (authors with slightly different names that refer to the same person). 
- Removed all unknown authors (anyone without a wikipedia page or website) 
- All author names now match the name on the person's wikipedia page
- All authors have a `bio` and a `link` the person's wikipedia page
- Removed over 100 low quality quotes
- Fixed all spelling errors in the data
- Fixed a number of grammatical errors in the quotes. I don't have an automated way check the entire collection for grammar. But I went through it manually and hopefully fixed most of the issues. I will continue to fix any other mistakes that people find.  

Again, if anyone is interested in helping to curate/maintain the collection of quotes, please let me know.
