### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by PLR2388** [lukePeavey/quotable#163]
The API is currently down. I try to access it via : https://api.quotable.io/random 

Can you look at it?

Thank you :)

**Comment by lukePeavey** [comment]
The API is currently down due to a high volume of automated requests that is overloading our server.   Our Atlas deployment doesn't have the resources to handle 15 million requests per day.  The hosting costs for this project are already way too high for a free API, so we cannot scale up.  

For now the API will be down until further notice (possibly a few days) while I figure out what to do.  I think we will need to add a rate limit and possibly authentication to prevent abuse. 

I apologize to everyone for the inconvenience.  I will post an update as soon as I have more details. **Feel free to comment but please don't open a new issue to report that API is down**

**Comment by lukePeavey** [comment]
Adding a rate limit, currently 60 requests per minute (by IP address).  This will likely change. For now I am just trying to get the API up and running again...

**Comment by lukePeavey** [comment]
If you are using this for a project that will be impacted by a rate limit, please open an issue (or discussion) and let me know.

**Comment by lukePeavey** [comment]
This issue has been resolved. There has not been any additional downtime since we added the rate limit a few days ago. 

For updates or comments regarding the rate limit, please see issue #165. 

Thanks to @PLR2388  and others for reporting this.
