### ISSUE TITLE
Request for Limit Parameter in /random Endpoint

### ISSUE THREAD

**Issue by eliasljubec** [lukePeavey/quotable#173]
Hello, @lukePeavey,

In my opinion, it would be beneficial to include a "limit" parameter for the **/random** endpoint, which would allow users to retrieve multiple random quotes. Adding this feature would enhance the user experience by providing increased randomness and would make for a valuable addition to the service.

Sincerely,
Elias

**Comment by lukePeavey** [comment]
Yeah that would a good feature. 

The problem is: the response format of the /random endpoint is a single quote object; it's not set up to return an array of quotes. 

So this endpoint can't return multiple quotes without a breaking change.


We could add another endpoint that returns a list of random quotes

**Comment by lukePeavey** [comment]
Will submit PR shortly

**Comment by lukePeavey** [comment]
🚀  This is live now.

[api.quotable.io/quotes/random?limit=3](https://api.quotable.io/quotes/random?limit=3)
