### ISSUE TITLE
[Feature Request] Random quote by specific author

### ISSUE THREAD

**Issue by lein1013** [lukePeavey/quotable#40]
I wonder if there is a way to get quotes just from one or several selected authors?
like
`GET /random?authorid=zgMVt2guVo7p,qsaptKSHuLDU`
or
`GET /random?author="Zig Ziglar","Laozi"`

**Comment by lukePeavey** [comment]
That's a good idea. We can definitely do that

**Comment by lukePeavey** [comment]
One thought....

The `tags` param takes a comma separated list, which translates to an `AND`  query (with "tag-one" `AND` "tag-two"), or a `|` separated list, which translates to an `OR` query (with "tag-one" `OR` "tag-two").

For consistency, would it make sense for this param to take a `|` separated  list  since its an `OR` query (by "author-one" `OR` "author-two"). 

Let me know what you think.

**Comment by lukePeavey** [comment]
If you would like to submit a PR for this, please feel free. If not, I can do it next weekend. 

https://github.com/lukePeavey/quotable/blob/7e854722d3fb67ebc013e331ca789cf82da95e54/src/controllers/quotes/randomQuote.js#L12-L14

```js
if (authorId) {
  filter.authorId = { $in: authorId.split('|') }
}

if (author) {
  filter.author = { $in: author.split('|') }
}
```

**Comment by raxraj** [comment]
@lukePeavey, 
First of all, I like this so much, I use it almost every time that I could.
Is this still open? I am up for this.

**Comment by DanielXYZ2000** [comment]
Nothing done from my side, but I would be happy to see this feature soon :-)

**Comment by lein1013** [comment]
Nothing done from my side, but I would be happy to see this feature soon :-)

**Comment by lukePeavey** [comment]
@raxraj did you want to work on this? If so it's all yours

**Comment by raxraj** [comment]
@lukePeavey @lein1013 , Awesome, 
I'll get right on it.
