### ISSUE TITLE
Add guide for new contributors.

### ISSUE THREAD

**Issue by marekdano** [lukePeavey/quotable#6]
I'm a new contributor. It'll be really great if a brief contributing guide exists in this project. Having a CONTRIBUTING.md file or something else with the contributing instructions.

So far I found that I need to do following steps before doing any changes in the codebase.

1. Making sure that Node and MongoDB are installed on my local machine
2. Create database of "quotable" on MongoDB
3. Pass environment variable of **MONGODB_URI** when seeding database or starting the app and integration tests, e.g. "MONGODB_URI=mongodb://localhost:27017/quotable"

seeding database with
```
MONGODB_URI=mongodb://localhost:27017/quotable npm run database:seed data/sample
```

starting tests 
```
MONGODB_URI=mongodb://localhost:27017/quotable npm test
```

starting the app 
```
MONGODB_URI=mongodb://localhost:27017/quotable npm run start
```

**Comment by lukePeavey** [comment]
Below is an initial draft of Contributor Guidelines. Please let me know if you have any feedback!

**Comment by lukePeavey** [comment]
All contributions are greatly appreciated!!

## Issues

- Feature requests/enhancements
- Bug reports
- Questions/feedback

## Pull Requests

1. [Fork][fork-a-repo] the repository on GitHub.

2. [Clone][cloning-a-repo] the forked repo to your local machine.

3. Create a new [feature branch][feature-branch] from master

4. Commit your changes

5. Push your changes back up to your fork.

6. When you're ready, submit a [pull request][pull-requests] so that we can review your changes

NOTE: If you have an existing fork, make sure to pull the latest changes from the upstream repository before working on a new contribution.

```sh
$ git remote add upstream https://github.com/lukePeavey/quotable.git
$ git pull upstream master
```

### Running the API Locally

If you are working on changes to the source code, you will want to run the server locally so you test your changes as you work.

**Requirements**

- Node >= 12.x
- NPM >= 6.x
- MongoDB

**1. Create a database**

You can install and run MongoDB locally, or use a cloud-based service like [MongoDB Atlas](https://cloud.mongodb.com/) (recommended).

Using MongoDB Atlas:

- Follow the instruction in the [getting started][mongodb/atlas] guide to provision a new database.
- Open the "Connect" dialog and select "Connect to Your Application" to get the connection string.

**2. Environment Variables**

Create a file called `.env` in the root directory of the project.

Set `MONGODB_URI` to the connection string for your database.

```dosini
MONGODB_URI=mongodb://<user>:<password>@ds013911.mlab.com:13911/quotable
```

**3. Install dependencies**

```sh
npm run install
```

**4. Seed the database**

This will populate your database with the sample data included in the repo.

```sh
$ npm run database:seed
```

**4. Start the Server**

```sh
$ npm run start
```

**5. Running Tests**

```sh
$ npm run test --watchAll
```

[mongodb/atlas]: https://www.mongodb.com/cloud/atlas
[mongodb/atlas/docs]: https://www.mongodb.com/cloud/atlas
[fork-a-repo]: https://help.github.com/en/articles/fork-a-repo
[cloning-a-repo]: https://help.github.com/en/articles/cloning-a-repository
[feature-branch]: https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
[pull-requests]: https://help.github.com/en/articles/about-pull-requests

**Comment by marekdano** [comment]
Thanks for the putting it down, @lukePeavey!!! It's a very good guide. I have a just small comment.

* I'd modify the sentence with the name of the database in the section of Create a database

*Follow the instruction in the getting started guide to provision a new database called **quotable**.*
